Create a 10x50 matrix with random numbers using numpy.

Print the shape of the matrix.

Ask from the user for a row number and print the row given.

Do the same for a column.

In [20]:
import numpy as np

matrix = np.random.randint(-99, 100, size=(10, 50))

# Print the shape of the matrix
print("Matrix shape:", matrix.shape)

# Ask from the user for a row number and print the row given
row = input("Enter a row number: ")
print("Row number", row, ":", matrix[int(row)])

# Ask from the user for a column number and print the column given
col = input("Enter a column number: ")
print("Column number", col, ":", matrix[:,int(col)])

Matrix shape: (10, 50)
Enter a row number: 7
Row number 7 : [-35  83 -28 -95 -88  30  12  62  48  25  23  26 -98  16 -58 -96  32 -62
   9  55   9 -12  87   3  -8 -63  52 -20 -14  80 -64  39 -20 -84  24  69
 -20 -22  68 -64 -27  58  77   7  42  23  54 -24 -64 -91]
Enter a column number: 8
Column number 8 : [-95 -92 -39 -23  97 -60  79  48  98 -19]


Create the following matrices and calculate their dot product.

$$ \left[
\begin{matrix}
    5 & 1 & 2 \\
    1 & 2 & 1 \\
    1 & 2 & 1 \\
\end{matrix}
\right] $$


$$ \left[
\begin{matrix}
    1 & 2 & 3 \\
\end{matrix}
\right] $$

In [ ]:
matrix_1 = np.array([[5, 1, 3], [1, 2, 1], [1, 2, 1]])
matrix_2 = np.array([[1, 2, 3]])

dot_product_1 = np.dot(matrix_1, matrix_1)
dot_product_2 = np.inner(matrix_2, matrix_2)

print(dot_product_1)
print(dot_product_2)

[[29 13 19]
 [ 8  7  6]
 [ 8  7  6]]
[[14]]


Given the following matrices calculate their (matrix) multiplication.
- A*B
- A*C

A
$$ \left[
\begin{matrix}
    1 & 0 \\
    0 & 1 \\
\end{matrix}
\right] $$

B
$$ \left[
\begin{matrix}
    4 & 1 \\
    2 & 2 \\
\end{matrix}
\right] $$

C
$$ \left[
\begin{matrix}
    1 & 2 \\
\end{matrix}
\right] $$



In [5]:
A = np.array([[1, 0], [0, 1]])
B = np.array([[4, 1], [2, 2]])
C = np.array([[1, 2]])

# A*B
AB = np.dot(A, B)

# Transpose C
C = C.T
# A*C
AC = np.dot(A, C)

print("A*B =", '\n', AB)
print("A*C =", '\n', AC)

A*B = 
 [[4 1]
 [2 2]]
A*C = 
 [[1]
 [2]]


Find the third power of this matrix.
$$ \left[
\begin{matrix}
    0 & 1 \\
    -1 & 0 \\
\end{matrix}
\right] $$

In [9]:
matrix = np.array([[0, 1], [-1, 0]])

matrix_3_power = np.linalg.matrix_power(matrix, 3)

print(matrix_3_power)

[[ 0 -1]
 [ 1  0]]


Find the determinant of this matrix.

$$ \left[
\begin{matrix}
    1 & 2 \\
    3 & 4 \\
\end{matrix}
\right] $$

In [14]:
matrix = np.array([[1, 2], [3, 4]])

determinant = np.linalg.det(matrix)

print(determinant)

-2.0000000000000004


Use the functions ‘eye’ and ‘ones’ from numpy to create 4x4 matrices. Find their ranks.

In [12]:
matrix_1 = np.eye(4)
matrix_2 = np.ones((4,4))

rank_1 = np.linalg.matrix_rank(matrix_1)
rank_2 = np.linalg.matrix_rank(matrix_2)

print("Rank of matrix using 'eye':", rank_1)
print("Rank of matrix using 'ones':", rank_2)

Rank of matrix using 'eye': 4
Rank of matrix using 'ones': 1


Find the inverse of this matrix.
$$ \left[
\begin{matrix}
    2 & 2 & 1 \\
    1 & 3 & 1 \\
    1 & 2 & 2 \\
\end{matrix}
\right] $$

In [15]:
matrix = np.array([[2, 2, 1], [1, 3, 1], [1, 2, 2]])
inverse = np.linalg.inv(matrix)
print(inverse)

[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


Find the pseudo inverse of this matrix.
$$ \left[
\begin{matrix}
    2 & 8 \\
    1 & 4 \\
\end{matrix}
\right] $$

In [16]:
matrix = np.array([[2, 8], [1, 4]])

pseudo_inverse = np.linalg.pinv(matrix)

print(pseudo_inverse)

[[0.02352941 0.01176471]
 [0.09411765 0.04705882]]


Find the eigenvalues and eigenvectors of this matrix.
$$ \left[
\begin{matrix}
    1 & -1 \\
    1 & 1 \\
\end{matrix}
\right] $$

In [17]:
A = np.array([[1, -1], [1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [1.+1.j 1.-1.j]
Eigenvectors: [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]
